# Generated by Django 2.2.6 on 2020-01-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_1',
            field=models.ImageField(default='post_images/default.png', upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='img_2',
            field=models.ImageField(default='post_images/default.png', upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='img_3',
            field=models.ImageField(default='post_images/default.png', upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='img_4',
            field=models.ImageField(default='post_images/default.png', upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='img_5',
            field=models.ImageField(default='post_images/default.png', upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='post_images/default.png', upload_to='post_images'),
        ),
    ]
