# Generated by Django 2.2.6 on 2020-01-20 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribed',
            name='subs',
        ),
        migrations.AddField(
            model_name='subscribed',
            name='subs',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
