# Generated by Django 2.2.6 on 2020-01-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200120_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_time']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='img_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img_5',
        ),
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
