# Generated by Django 2.2.6 on 2020-01-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_user_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_reaction',
        ),
    ]
