# Generated by Django 2.2.6 on 2020-01-29 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20200122_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_reaction',
            field=models.ManyToManyField(blank=True, related_name='react', to=settings.AUTH_USER_MODEL, verbose_name='Реакция юзеров'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
