# Generated by Django 2.2.6 on 2020-02-19 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200204_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='lk_post', to='core.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='lk_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='like',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lk_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
