# Generated by Django 2.2.6 on 2020-03-08 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_post_dislk_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_dislike_react',
            field=models.ManyToManyField(blank=True, related_name='user_dislike_react', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user_like_react',
            field=models.ManyToManyField(blank=True, related_name='user_like_react', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
